### ISSUE TITLE
App Bundles not returned for an artistid lookup

### ISSUE THREAD

**Issue by radianttap** [danielamitay/DAAppsViewController#21]
When I use this URL with proper User-Agent, resulting JSON does not include app bundles.

`https://itunes.apple.com/lookup?id=XX&entity=software`

Anyone knows what should be added/changed? When using this in Safari, it shows the bundles, thus I think this is due to User Agent string. What's the correct one..?

**Comment by danielamitay** [comment]
Can't repro, let me know if anything changes
