### ISSUE TITLE
Can't make purchase using SKStoreProductViewController. Apple Store Purchase works.

### ISSUE THREAD

**Issue by Jhonny12345** [danielamitay/DAAppsViewController#32]
Hi, 

I am using DAAppsViewController in my project and using iPAD Mini device (iOS 8.3) for testing. It is showing all of my apps and launching SKStoreProductViewController. When I try to make  a purchase then it asks to sign in with APPLE id. I am using my existing APPLE id with correct password (tried several times) but I am always getting following error 

"The Apple ID you entered couldn't be found or your password is incorrect"

But when I click on "Store" at the Top right corner and try to make a purchase directly on APPLE STORE using the **SAME** Apple id and password then it always works. But in that case, I had to live my app while I need in-app store purchase without leaving my app.

I am just not sure that SKStoreProductViewController is working or not. **Can you purchase and download an app using SKStoreProductViewController on a device that has ios 8.3+ version? Can you please check and confirm that it is working on any ios version greater than equal to ios 8.3?**

My Apple id belongs to INDIA Store and valid for purchases in INDIA. I have seen in your code that it is not restricted to US Only so it should work in INDIA store if it is working for US Store.

**Does it only work for an apple id that is valid for purchases in US APPLE STORE?** 

I tried changing my iPad setting by setting Country= USA and language = US English but it still doesn't work with my apple id as it is valid for INDIA store. I didn't create a new apple id for US store as I think it is against the iTunes policy to use multiple accounts.

How am i supposed to fix this issue?

If it is not working on new iOS versions then please fix this issue. If it is somehow restricted to US only purchase then please add in-app app purchase functionality for other countries too.

Please reply.

Thanks.

**Comment by danielamitaysc** [comment]
@Jhonny12345 is this occurring when you build to your device locally, or when running your app downloaded from the App Store?

Unfortunately `SKStoreProductViewController` doesn't work in non-AppStore apps. This is a known behavior, though unfortunately I do not believe it is documented.

In any case, `DAAppsViewController` is simply presenting a vanilla `SKStoreProductViewController`, so there is little that it can do to either cause or fix this issue.

**Comment by danielamitay** [comment]
@Jhonny12345 is this occurring when you build to your device locally, or when running your app downloaded from the App Store?

Unfortunately SKStoreProductViewController doesn't work in non-AppStore apps. This is a known behavior, though unfortunately I do not believe it is documented.

In any case, DAAppsViewController is simply presenting a vanilla SKStoreProductViewController, so there is little that it can do to either cause or fix this issue.

**Comment by Jhonny12345** [comment]
This is occurring when I am building and running locally on my device (using Xcode) for testing purpose. I didn't download my app from Apple store. 

So if it is intended behavior then it means once my app is approved by apple then it will work on devices when people will download my app from Apple Store.

Please confirm.

Thanks

**Comment by danielamitay** [comment]
Yes that is correct.

**Comment by Jhonny12345** [comment]
Cool. 

Thank you very much. I truly appreciate your quick response.

**Comment by ly541349042** [comment]
Hey, I also met the same problem like yours, and I asked Apple's Technical Support Engineer.
I got an answer , I paste it here. Hopes can help.

>    <"The Apple ID you entered couldn't be found or your password is incorrect”>
> That is the expected behavior. Your sample app is running in the Sandbox; you cannot make any purchases nor download anything using SKStoreProductViewController in the Sandbox. Note that the Sandbox only uses test user accounts rather than real ones. 

   
Be relax to use SKStoreProductViewColler. :)
