### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by iqbal92** [danielamitay/DAAppsViewController#35]
DAAppsViewCell.m

self.nameLabel.text = appObject.name;  //Thread 1: EXC_BAD_ACCESS (code=1, address=0x25b8bbec8)
self.genreLabel.text = appObject.genre;
[self.purchaseButton setTitle:appObject.formattedPrice forState:UIControlStateNormal];

**Comment by ricsantos** [comment]
Sounds like the same issue as #25 

Are you using CocoaPods with frameworks? If so, installing the pod like this should fix the problem:

    pod 'DAAppsViewController', :git => 'https://github.com/danielamitay/DAAppsViewController.git', :branch => 'master'
