### ISSUE TITLE
Adding this to a project in storyboard

### ISSUE THREAD

**Issue by dunc77** [danielamitay/DAAppsViewController#8]
Quick question on this, can anybody tell me how to add this to my project? i want it on page 5 in Storyboard mode but this code only loads up on the main page and the project does not include an xib or storyboard as they are not needed

Any idea anyone?

**Comment by lunarbase** [comment]
The question is: have YOU read the README? 😃 There is nothing there telling how to integrate this with a storyboard app in terms of DAAppsViewController being an item on a storyboard, that is what the op seems to be asking.

**Comment by docash59** [comment]
This is what I've done:
1. Imported the project
2. **Ensured that the view (e.g.Settings/About screen) in Storyboard is embedded in a UINavigationController.** 
2. Added this to my .m:
```
DAAppsViewController *appsViewController = [[DAAppsViewController alloc] init];
[appsViewController loadAppsWithArtistId:@"ArtistId" completionBlock:nil];
[self.navigationController pushViewController:appsViewController animated:YES];
```

Thats about it. No need to add a new ViewController. Just link up to an IBAction and your done.
